#pragma once

#define FROM               "From"
#define TO                 "To"
#define FEE_ONG            "Fee"
#define GAS_FEE            "Gas fee"
#define PERCENTAGE         "%"
#define ONG_VIEW           " ONG"
#define ONT_VIEW           " ONT"
#define SIGNER             "Signer"
#define SENDER             "Sender"
#define DECIMALS           "Decimals"
#define DECIMALS_UNKNOWN   "Unknown"
#define AMOUNT             "Amount"
#define NBGL_MSG           "Message"
#define NBGL_PEER_PUBKEY   "Operation wallet public key"
#define TOTAL_WITHDRAW     "Total amount"
#define POS                "Stake amount"
#define STAKE_FEE          "Starting fee"
#define STAKE_FEE_ONG      "500 ONG"
#define MAX_AUTHORIZE      "Allowed user stake"
#define PEER_COST          "Fee Sharing Ratio (Node)"
#define STAKE_COST         "Fee Sharing Ratio (User)"
#define ADDRESS            "Address"
#define BLIND_SIGNING      "Blind signing"
#define NODE_AMOUNT        "Node amount"
#define ONE                "1"
#define TWO                "2"
#define BLIND_SIGN_TX      "Blind signing Transaction"
#define VERIFY_ONT_ADDRESS "Verify ONT address"

#define TRANSFER_TITLE   "Review transaction to send token"
#define TRANSFER_CONTENT "Sign transaction to send token?"

#define TRANSFER_FROM_TITLE   "Review transaction"
#define TRANSFER_FROM_CONTENT "Sign transaction?"

#define APPROVE_TITLE   "Review transaction to approve"
#define APPROVE_CONTENT "Sign transaction to approve?"

#define REGISTER_CANDIDATE_TITLE   "Review transaction to register a node"
#define REGISTER_CANDIDATE_CONTENT "Sign transaction to register a node?"
#define QUIT_NODE_TITLE            "Review transaction to quit the node"
#define QUIT_NODE_CONTENT          "Sign transaction to quit the node?"

#define ADD_INIT_POS_TITLE      "Review transaction to add initial stake"
#define ADD_INIT_POS_CONTENT    "Sign transaction to add initial stake?"
#define REDUCE_INIT_POS_TITLE   "Review transaction to reduce stake"
#define REDUCE_INIT_POS_CONTENT "Sign transaction to reduce stake?"

#define AUTHORIZE_FOR_PEER_TITLE      "Review transaction to stake"
#define AUTHORIZE_FOR_PEER_CONTENT    "Sign transaction to stake?"
#define UN_AUTHORIZE_FOR_PEER_TITLE   "Review transaction to unstake"
#define UN_AUTHORIZE_FOR_PEER_CONTENT "Sign transaction to unstake?"

#define CHANGE_MAX_AUTHORIZATION_TITLE   "Review transaction to edit allowed user stake"
#define CHANGE_MAX_AUTHORIZATION_CONTENT "Sign transaction to edit allowed user stake?"
#define SET_FEE_PERCENTAGE_TITLE         "Review transaction to edit fee sharing ratio"
#define SET_FEE_PERCENTAGE_CONTENT       "Sign transaction to edit fee sharing ratio?"

#define WITHDRAW_FEE_TITLE   "Review transaction to claim ONG"
#define WITHDRAW_FEE_CONTENT "Sign transaction to claim ONG?"
#define WITHDRAW_TITLE       "Review transaction to withdraw"
#define WITHDRAW_CONTENT     "Sign transaction to withdraw?"

#define BLIND_SIGNING_TITLE   "Review transaction"
#define BLIND_SIGNING_CONTENT "Accept risk and send transaction?"

#define PERSONAL_MSG_TITLE   "Review message"
#define PERSONAL_MSG_CONTENT "Sign message?"

#define BLIND_SIGNING_SWITCH_TEXT    "Blind signing"
#define BLIND_SIGNING_SWITCH_SUBTEXT "Enables transaction or msg blind signing"